services:
  # BACKEND (Express + Bun)
  backend:
    build:
      context: ./library-be
      dockerfile: Dockerfile
    container_name: library_backend
    restart: always
    ports:
      - "3000:3000" # Akses di localhost:3000
    env_file:
      - ./library-be/.env # Load env dari file lokal (JANGAN DI-COMMIT)
    depends_on:
      - postgres # Tunggu DB lokal hidup (opsional jika pakai DB Online)

  # FRONTEND (React + Nginx)
  frontend:
    build:
      context: ./library-fe
      dockerfile: Dockerfile
    container_name: library_frontend
    restart: always
    ports:
      - "80:80" # Akses di localhost:80
    depends_on:
      - backend

  # Database Local (PostgreSQL) - Opsional kalau mau pake lokal
  postgres:
    image: postgres:16-alpine
    container_name: library_postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-library_db}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Database GUI Viewer
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: postgres

volumes:
  postgres_data:
